### PR TITLE
Tentative fix for UICR-45

### PR DESCRIPTION
**Pull request by MikeTaylor**
XXX needs to be inspected by someone who knows the code!

### CODE REVIEW

**Comment by MikeTaylor** [comment]
@kurtnordstrom Please see background from UICR-45. I will copy the relevant parts from there so you don't have to wade through the long comment stream:

> What we are interested in displaying [for a reserved item in the UI] is what we might call the "effective permanent location" of the item — that is, either its own permanent location (when defined) or that of its holding otherwise. We do not want to display here anything that relates to temporary locations.
>
> The problem is that the item record contains its own permanent location — do we can and do display that when it is set — but not that of the holding that it belongs to. So for items that rely on their holding to specify permanent location, we can't see that permanent location. We can see effective location, which is supplied as part of the item record — but as we know, that unhelpfully changes when the temporary location is set.

...

> I think there is a simple (for me!) solution.
>
> I believe that when you reserve an item, you fetch both the item record and its associated holding, correct? (And maybe the instance as well, but that's not important at the moment.) If I remembered this right, you use both the item and the holding (and maybe the instance) to populate the reserve's copiedItem.
>
> If that's so, that couldn't you simply check both the item and the holding when determining the permanentlocationId to copy into copiedItem?

That is what this simple PR tries to achieve. Is it correct?

**Comment by MikeTaylor** [comment]
OK, I see this code won't compile, saying:
> /home/jenkins/workspace/nt-location-from-item-or-holding/src/main/java/org/folio/coursereserves/util/CRUtil.java:[224,81] bad operand types for binary operator '||'>
> first type:  java.lang.String
> second type: java.lang.String

Bizarre the Java doesn't support shortcut operators, but never mind. The intent of the code is obvious, I think, so if you're happy with the intent, I will trust you to write it in a way that satisfies the Java gods.

**Comment by kurtnordstrom** [comment]
Time to do the SonarCloud dance!

**Comment by MikeTaylor** [comment]
Looks like this has fixed the problem: see new UICR-45 comment for discussion. Thanks!

**Pull request merged**
